---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - image: {{ .Values.image.repository | required "image.repository must be set via --set" }}:{{ .Values.image.tag | required "image.tag must be set via --set" }}
        name: {{ .Release.Name }}
        ports:
        - containerPort: {{ .Values.app.targetPort | int }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.app.port | int }}
      targetPort: {{ .Values.app.targetPort | int }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metdata:
  name: {{ .Values.app.name }}
  annotations:
    alb.ingress.io/group.name
    alb.ingress.kubernetes.io/group.order: 100
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernets.io/scheme: internet-facing
spec:
  rules:
    - host: "{{ .Values.app.name }}.salientapps.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.app.name }}
                port:
                  number: 8080