apiVersion: v2
name: ephemeral
description: A Helm chart for deployment of ephemeral eks clusters
type: application
version: 0.1.0
appVersion: 0.1.0
keywords:
  - ephemeral
  - eks
  - helm
  - kubernetes
  - deployment
maintainers:
  - name: DevSpace
    email: devspaceml@gmail.com