apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gem-app.fullname" . }}-config
  labels:
    {{- include "gem-app.labels" . | nindent 4 }}
data:
  app.conf: |
    server {
      port: {{ .Values.service.targetPort }}
      environment: {{ index .Values.env 0 "value" | default "production" }}
    }  