{{- if .Values.ingressRoute.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-strip-prefix
  namespace: {{ .Release.Namespace }}
spec:
  stripPrefix:
    prefixes:
      - "/{{ .Release.Name }}"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  entryPoints:
    {{- toYaml .Values.ingressRoute.entryPoints | nindent 4 }}
  routes:
    kind: Rule
    - match: "Host(`{{ .Values.ingressRoute.host }}`) && PathPrefix(`/{{ .Release.Name }}`)"
      middlewares:
        - name: {{ .Release.Name }}-strip-prefix
          namespace: {{ .Release.Namespace }}
      services:
        - name: {{ .Release.Name }}-service
          port: {{ .Values.app.port }}
    kind: Rule
    - match: "Host(`{{ .Values.ingressRoute.host }}`) && PathPrefix(`/monitoring/grafana`)"
      services:
        - name: grafana
          namespace: monitoring
          port: 80
  tls:
    secretName: {{ .Release.Name }}-tls
{{- end }}
