name: Dev Infrastructure

on:
  push:
    branches:
      - develop
    paths:
      - 'Infrastructure/dev/**'
  workflow_dispatch:
     inputs:
       environments:
         description: 'Environments to display'
         required: false
         default: dev
         type: string

env:
  TF_VERSION: "1.5.0"
  AWS_REGION: "us-east-1"
  CLUSTER_NAME: "dev-cluster"
  EKS_CLUSTER_NAME: "dev-cluster"

jobs:
  deploy-cluster:
    name: deploy-eks-cluster
    runs-on: ubuntu-latest
    outputs:
      cluster-endpoint: ${{ steps.cluster-info.outputs.endpoint }}
      cluster-ca: ${{ steps.cluster-info.outputs.certificate_authority }}
      cluster-arn: ${{ steps.cluster-info.outputs.arn }}

    steps:  
      - name: checkout-code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::586098609239:role/GitHubActionsRole
          role-session-name: GitHub-Actions-OIDC-Session
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Prepare Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false

      - name: Terraform Init
        working-directory: Infrastructure/environments/dev
        run: |
          terraform init

      - name: Terraform Validate
        working-directory: Infrastructure/environments/dev
        run: terraform validate

      - name: Terraform Format Check
        working-directory: Infrastructure/environments/dev
        run: terraform fmt -check

      - name: Terraform Plan
        working-directory: Infrastructure/environments/dev
        run: |
          terraform plan -var-file="dev.tfvars" -out=deploy-dev-eks.tfplan

      - name: Terraform Apply
        working-directory: Infrastructure/environments/dev
        run: |
          terraform apply -auto-approve deploy-dev-eks.tfplan

      - name: Check Cluster Readiness
        run: |
          echo "Waiting for Cluster readiness..."
          aws eks wait cluster-active --name ${{ env.CLUSTER_NAME }} --region ${{ env.AWS_REGION }}
          echo "Cluster now available"    
          
      - name: Get Cluster Info
        id: cluster-info
        working-directory: Infrastructure/environments/dev
        run: |
          ENDPOINT=$(terraform output -raw cluster-endpoint)
          CA_DATA=$(terraform output -raw cluster_certificate_authority_data)
          CLUSTER_ARN=$(terraform output -raw cluster_arn)

          echo "endpoint=$ENDPOINT" >> $GITHUB_OUTPUT
          echo "certificate_authority=$CA_DATA" >> $GITHUB_OUTPUT
          echo "arn=$CLUSTER_ARN" >> $GITHUB_OUTPUT

  update-kubeconfig:
    name: update-kubeconfig
    runs-on: ubuntu-latest
    needs: deploy-cluster

    steps:
      - name: checkout-code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::586098609239:role/GitHubActionsRole
          role-session-name: GitHub-Actions-OIDC-Session
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: kubeconfig update
        run: |
          aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER_NAME }}
          mkdir -p ~/.kube-backup
          cp ~/.kube/config ~/.kube-backup/config
          kubectl cluster-info
          kubectl get nodes

  domain-dns-update:
      - name: domain-dns-update
        runs-on: ubuntu-latest
        needs: update-kubeconfig
        steps:
        - name: wait for manual dns updates
        run: |
          echo "Pausing 3 minutes to allow manual dns updates"
          sleep 180
          echo "*** Resuming deployment ****"

  deploy-remaining:
    runs-on: ubuntu-latest
    needs: [deploy-cluster, domain-dns-update]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::586098609239:role/GitHubActionsRole
          role-session-name: GitHub-Actions-OIDC-Session
          aws-region: ${{ env.AWS_REGION }}  

      - name: Terraform Init 
        working-directory: Infrastructure/environments/dev
        run: |
          terraform init

      - name: Terraform Validate
        working-directory: Infrastructure/environments/dev
        run: terraform validate

      - name: Terraform Format Check
        working-directory: Infrastructure/environments/dev
        run: terraform fmt -check

      - name: Terraform plan
        working-directory: Infrastructure/environments/dev
        run: |
          terraform plan -var-file="dev.tfvars" -out=complete-dev-eks.tfplan

      - name: Terraform Apply
        working-directory: Infrastructure/environments/dev
        run: |
          terraform apply -auto-approve complete-dev-eks.tfplan